CREATE TABLE IF NOT EXISTS "legacy-grow-app_strain" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "legacy-grow-app_strain_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"type" "genetic_type" NOT NULL,
	"description" text,
	"flowering_time" integer,
	"thc_potential" numeric(4, 1),
	"cbd_potential" numeric(4, 1),
	"created_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "legacy-grow-app_strain" ADD CONSTRAINT "legacy-grow-app_strain_created_by_legacy-grow-app_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."legacy-grow-app_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "strain_name_idx" ON "legacy-grow-app_strain" USING btree ("name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "strain_type_idx" ON "legacy-grow-app_strain" USING btree ("type");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "strain_created_by_idx" ON "legacy-grow-app_strain" USING btree ("created_by");